# pytest测试失败
def test_fail():
    assert (1, 2, 3) == (3, 2, 1)