# 测试基础
写代码并不光是开发，测试也是其中的组成部分。要想测试就必须运行程序，有时可能还需要外部环境的支持，比如编写了一个处理文件的程序，那么还需提供要测试的文件。  
在编译型语言中，将不断重复编辑、编译、运行的循环。有些情况下，编译就会出现问题。在Python中，不存在编译环节，只有编辑和运行阶段。测试就是运行程序。  
这一章主要介绍测试的基本知识。如何养成在编程中进行测试的习惯，并介绍一些可帮助编写测试的工具。除了标准库中的测试和性能分析工具，我还将介绍如何使用代码分析器PyChecker和PyLint。

## 16.1 先测试再编码
在写代码的过程中，有可能面临变化，所以为各个部分编写单元测试就非常重要，因为它可以在你修改代码之后，保证你的代码还能实现预期的功能，通过之前的测试。
极限编程引入了"测试一点点，再编写一点点代码"的理念。虽然这种理念和直觉不太相符，却很管用，胜过"先写代码再测试"的做法。  
换言之，测试在前，编码在后。这也称为**测试驱动的编程**。  
### 16.1.1 准确的需求说明
开发软件时，必须要先知道软件要解决那些问题，实现哪些功能。为此可以编写软件需求文档，描述程序必须满足何种需求。而且还可以在开发完成后，核对需求是否得到了满足。
好消息是，你可使用Python来描述需求，并让解释器检查是否满足了这些需求!  
这里的理念是先编写测试，再编写让测试通过的程序。测试程序就是需求说明，可帮助确保程序开发过程紧扣这些需求。  
比如：写一个模块，里面有个根据矩形的长宽计算面积的函数。为此，我们应该先编写测试代码。
```python
from area import rect_area
height = 4
width = 5
correct_answer = 20
answer = rect_area(height, width)
if answer == correct_answer:
    print('Test passed')
else:
    print('Test failed')
```
如果我们在area.py中把代码写成了下面这样，那么是通过不了测试的
```python
def rect_area(height, width):
    return height * height
```
先编写测试在编写代码并不是为了发现bug，而是为了检查代码是否管用。采取下面的态度大有裨益:除非有相应的测试，否则该功能就并不存在，或者说不是真正意义上的功能。

### 16.1.2 做好应对变化的准备
自动化测试的意义不止在于编写程序时提供帮助，还在于修改代码时避免累积错误，尤其当代码规模逐渐变大的情况下。代码修改时不可避免的，而修改代码又是有风险的。
修改代码的时候往往会引入一些bug，如果代码设计良好（比如使用了适合的抽象和封装），修改带来的影响就是局部的，只会影响很小一段代码。这意味着你能够确定bug的范围，
因此调试起来更加容易。
> 代码覆盖率  
> 覆盖率是一个重要的测试概念。优秀测试套件的目标之一是确保较高的覆盖率，为此可使用覆盖率工具，它们测量测试期间实际运行的代码所占的比例。  
> 你可能觉得详尽地测试各个方面让人不堪重负。不用担心，你无需测试数百种输入和状态变量组合，至少开始的时候不用。在测试驱动的编程中，最重要的一点是在编码期间反复地运行方法(函数或脚本)，以不断获得有关你做法优劣的反馈。如果以后要进一步确信代码是正确的(覆盖率也很高)，可随时添加测试。

### 16.1.3 测试四部曲
测试驱动开发过程的各个阶段：
1. 确定需要实现的新功能。可将其记录下来，再为止编写一个测试。
2. 编写实现功能的框架代码，让程序能够运行（不存在语法错误等问题），但测试无法通过。确认测试失败是很重要的，万一测试代码写的有问题，什么情况下都能通过测试，那测试就没有意义。
不断重复下面这个过程：确定测试失败后，再试图让它成功。
3. 编写让测试刚好通过的代码。在这个阶段，无需完全实现所需的功能，而只要让测试通过即可。这样，在整个开发阶段，都能够让所有的测试通过(首次运行测试时除外)， 即便是刚着手实现功能时亦如此。
4. 改进(重构)代码以全面而准确地实现所需的功能，同时确保测试依然能够成功。

提交代码时，必须确保它们处于健康状态，即没有任何测试是失败的。测试驱动编程倡导者都是这么说的。

## 16.2 测试工具
如果自己编写测试代码，那么工作量是巨大的。标准库提供了两个模块可以自动完成测试过程。
+ unittest：一个通用的测试框架
+ doctest：一个更简单的模块，是为检查文档而设计的，但也非常适合来编写单元测试。

### 16.2.1 doctest
doctest模块可以读取到代码中的文档字符串，并在其中找出类似于交互式解释器的测试用例，并执行。  
比如有一个计算平方的函数，我们编写文档字符串，并添加类似交互式解释器的用例，之后再在模块末尾添加__main__进行测试
```python
# my_math.py
def square(x):
    """
    计算平方并返回结果
    >>> square(2)
    4
    >>> square(3)
    9
    """
    return x * x


if __name__ == '__main__':
    import my_math
    from doctest import testmod
    # 函数doctest.testmod读取模块中的所有文档字符串， 
    # 查找看起来像是从交互式解释器中摘取的示例，再检查这些示例是否反映了实际情况。
    testmod(my_math)
```
通过增加-v参数来执行my_math.py，可以看到测试情况
```shell
(venv) zjx@MacBook-Pro doctest % python my_math.py -v
Trying:
    square(2)
Expecting:
    4
ok
Trying:
    square(3)
Expecting:
    9
ok
1 items had no tests:
    my_math
1 items passed all tests:
   2 tests in my_math.square
2 tests in 2 items.
2 passed and 0 failed.
Test passed.

```

### 16.2.2 unittest
unittest相比于doctest更加灵活和强大。
> 标准库里还包含另外两个有趣的单元测试工具：pytest和nose

下面看一个示例，假如要编写一个名为my_math的模块，其中包含一个计算乘积的函数product。按照测试驱动开发的思想，应该先使用模块unittest中的TestCase类编写一个测试。
```python
# test_my_math.py
import unittest, my_math


class ProductTestCase(unittest.TestCase):
    def test_integers(self):
        for x in range(-10, 10):
            for y in range(-10, 10):
                p = my_math.product(x, y)
                self.assertEqual(p, x * y, 'Integer multiplication failed')

    def test_float(self):
        for x in range(-10, 10):
            for y in range(-10, 10):
                x = x / 10
                y = y / 10
                p = my_math.product(x, y)
                self.assertEqual(p, x * y, 'Float multiplication failed')

if __name__ == '__main__':
    unittest.main()
```
函数unittest.main负责替你运行测试：它将实例化所有的TestCase子类，并运行所有以test开头的方法。
> 提示  
> 如果你定义了方法setUp和tearDown，它们将分别在每个测试方法之前和之后执行。你可使用这些方法来执行适用于所有测试的初始化代码和清理代码，这些代码称为测试夹具(test fixture)。

TestCase类还包含很多与assertEqual类似的方法，如assertTrue、assertIsNotNone和assertAlmostEqual。

模块unittest区分错误和失败。错误指的是引发了异常，而失败是调用failUnless等方法的结果。接下来需要编写框架代码，以消除错误——只留下失败。
这意味着只需创建包含如下内容的模块my_math(即文件my_math.py):
```python
def product(x, y):
    pass
```
此时运行测试会出现两条FAIL消息。
```shell
FF
======================================================================
FAIL: test_floats (__main__.ProductTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test_my_math.py", line 17, in testFloats
self.assertEqual(p, x * y, 'Float multiplication failed')
    AssertionError: Float multiplication failed
======================================================================
FAIL: test_integers (__main__.ProductTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test_my_math.py", line 9, in testIntegers
self.assertEqual(p, x * y, 'Integer multiplication failed')
    AssertionError: Integer multiplication failed 11 

----------------------------------------------------------------------
 Ran 2 tests in 0.001s FAILED (failures=2)
```
接下来需要让代码管用
```python
def product(x, y):
    return x * y
```
输出如下
```shell
.. 
---------------------------------------------------------------------- 
Ran 2 tests in 0.015s
OK
```
开头的两个.代表测试。  
我们可以测试一下不能通过测试的情况，使参数在为7和9的时候出错
```python
def product(x, y):
    if x == 7 and y == 9:
        return '我成心的'
    else:
        return x * y
```
输出结果：
```shell
Ran 2 tests in 0.007s

FAILED (failures=1)

Integer multiplication failed
63 != 我成心的

Expected :我成心的
Actual   :63
<Click to see difference>

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '我成心的' != 63 : Integer multiplication failed

```

## 16.3 超越单元测试
还有其他的测试程序的方法：源代码检查和性能分析。源代码检查是一种发现代码中常见错误或问题的方式。（有点儿像静态类型语言中编译器的作用）。
性能分析指的是搞清楚程序的运行速度到底有多快。这本书这一章节安排的顺序遵循了“使其管用，使其更好，使其更快”的规则。
单元测试先保证程序可用，源代码检查让程序更好，性能分析让程序更快。

### 16.3.1 使用PyChecker和PyLint检查源代码
长期以来，PyChecker都是用于检查Python源代码的唯一工具，能检查出函数提供的参数不对等错误。
之后出现了PyLint，它支持PyChecker提供的大部分功能，还有许多新功能，如变量名是否符合指定的命名约定、你是否遵守了自己的编码标准等。

可以通过pip命令安装PyLint：`pip install pylint`
安装完成后，可以以命令行脚本的方式运行，也可以作为模块导入。  

要使用PyChecker来检查文件，可运行这个脚本并将文件名作为参数，如下所示：
```shell
pychecker file1.py file2.py ...
```
使用PyLint检查文件时，需要将模块（或包）名作为参数：
```shell
pylint module
```
要获悉有关这两个工具的详细信息，可使用命令行开关-h来运行它们。运行这两个命令时，
输出可能非常多（pylint的输出通常比pychecker的多）。这两个工具都是可高度配置的，
你可指定要显示或隐藏哪些类型的警告。

下面看看如何结合使用单元测试和检查器。  
PyChecker和PyLint都可以作为模块导入，但它们并不是为了以编程方式使用而设计的。
导入pychecker.checker时，它会检查后续代码（包括导入的模块），并将警告打印到标准输出。
模块pylint.lint包含一个文档中没有介绍的函数Run，这个函数是供脚本pylint本身使用的。
它也将警告打印出来，而不是以某种方式将其返回。  
作者建议不要将这两个模块作为模块使用，而是用作命令行工具使用。在Python中，可通过模块subprocess来使用命令行工具。  

下面的代码在前面的测试脚本示例中添加了两个代码检查测试。
```python
import unittest, my_math
from subprocess import Popen, PIPE


class ProductTestCase(unittest.TestCase):
    def test_integers(self):
        for x in range(-10, 10):
            for y in range(-10, 10):
                p = my_math.product(x, y)
                self.assertEqual(p, x * y, 'Integer multiplication failed')

    def test_float(self):
        for x in range(-10, 10):
            for y in range(-10, 10):
                x = x / 10
                y = y / 10
                p = my_math.product(x, y)
                self.assertEqual(p, x * y, 'Float multiplication failed')
                
    # 在测试用例中，增加使用PyChecker进行检查的测试方法
    def test_with_PyChecker(self):
        # 开关-Q（quiet，意为静默
        cmd = 'pychecker', '-Q', my_math.__file__.rstrip('c')
        pychecker = Popen(cmd, stdout=PIPE, stderr=PIPE)
        self.assertEqual(pychecker.stdout.read(), '')

    def test_with_PyLint(self):
        # 开关-rn（其中n表示no）以关闭报告，这意味着将只显示警告和错误。
        cmd = 'pylint', '-rn', 'my_math'
        pylint = Popen(cmd, stdout=PIPE, stderr=PIPE)
        self.assertEqual(pylint.stdout.read(), '')

if __name__ == '__main__': unittest.main()
```
